"""initial revision

Revision ID: 200f1c0b3617
Revises: 
Create Date: 2022-05-08 19:45:39.596007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "200f1c0b3617"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
